# Site wide configuration

title: Kerr Spacetime
locale: en_US
description: A Web Tool for Visualizing Kerr Spacetime and Bound Geodesics
logo: #site-logo.png
search: true
#baseurl: "KerrSimulator"
url: http://localhost:4000
#url: https://jrivest3.github.io/KerrSimulator

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "tohost.sh"]


# Site owner
owner:
  name: Joe Rivest
  avatar: #bio-photo.jpg
  email: #you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: jrivest3
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
